#include "compute_root.h"
[[vk::push_constant]] ConstantBuffer<ComputeRoot> root;

[numthreads(16, 16, 1)]
void computeMain(uint3 dispatchID : SV_DispatchThreadID,
                 uint3 groupThreadID : SV_GroupThreadID,
                 uint groupIndex : SV_GroupIndex,
                 uint3 groupID : SV_GroupID) {
    uint3 gid = dispatchID;
    if (gid.x >= root.params[1] || gid.y >= root.params[2]) {
        return;
    }

    uint i = gid.y * root.params[1] + gid.x;
    uint packed = ((uint*)root.buffers[0])[i];
    uint r = packed & 255u;
    uint g = (packed >> 8u) & 255u;
    uint b = (packed >> 16u) & 255u;
    float a = float((packed >> 24u) & 255u) * (1.0 / 255.0);
    ((float4*)root.buffers[1])[i] = float4(
        ((float*)root.buffers[2])[r] * a,
        ((float*)root.buffers[2])[g] * a,
        ((float*)root.buffers[2])[b] * a,
        a
    );
}
